---
- name: Baseline Provisioning Wrapper
  hosts: all
  become: true
  gather_facts: false


  tasks:
    - name: Find Job Template ID
      uri:
        #url: https://ansibletower.net/api/v2/job_templates/name={{ job_template_name }}
        url: https://localhost/api/v2/job_templates/?name=Test+connectivity+to+hosts
        method: GET
        url_username: admin
        url_password: redhat
        force_basic_auth: true
        validate_certs: false
      register: job_template_json
      tags: find_id

    - set_fact:
        job_template_id: "{{ (job_template_json.json.results|first)['id'] }}"

    - debug:
        msg:
          - "Retrieving Job Template ID through Ansible Tower API"
          - "The Job Template ID is: {{ job_template_id }} "


    - name: Execute Job Template using template_id
      uri:
        #url: https://{{ ansible_tower_url }}/api/v2/job_templates/{{ job_template_id }}/launch/
        url: https://localhost/api/v2/job_templates/{{ job_template_id }}/launch/
        method: POST
        url_username: admin
        url_password: redhat
        force_basic_auth: true
        validate_certs: false
        status_code: 201
        #body_format: json
        #body: "{\"limit\":\"mnode1\"}"
      register: job_info
      until: (job_info.json.status == 'successful') or (job_info.json.status == 'failed') or (job_info.json.status == 'canceled') (job_info.json.status == 'error')
      #retries: 5
      #delay: 1

    - set_fact:
        job_status: "{{ job_info.json.status }}"

    - debug:
        msg:
          - "Launching Job Template using template_id retrieved in previous step"
          - "The Job status was reported as: {{ job_status }}"
